

service_list = [
    "instagram",
    "amazon",
    "Apple",
    "Deutsche Bahn",
    "Bundestag.de",
    "bvg",
    "basf",
    "beiersdorf",
    "bnp_paribas",
    "Chefkoch",
    "Deutsche Post AG (deutschepost.de)",
    "Discord",
    "fresenius medical care",
    "GR\u00dcNE",
    "facebook",
    "lotto",
    "Privacy Icons Forum",
    "Microsoft",
    "rewe",
    "Runtastic",
    "ryanair",
    "Tagesschau App",
    "takeda",
    "telefonica",
    "Telegram",
    "tesco",
    "techniker krankenkasse",
    "TU Berlin",
    "Twitch",
    "Twitter",
    "vw",
    "vinci",
    "verivox",
    "webde",
    "whatsapp",
    "ZDF Mediathek"
    "Zoom"
]
