version: '3.0'
#services:
#  rasa:
    #image: rasa/rasa:2.3.2-full
#    image: floramarleen/rasa:test_image_rasa
#    ports:
#      - 5005:5005
#    volumes:
#      - ./:/app
#    command: run -m models --port 5005 --cors "*" --enable-api --debug
#  app:
#    image: floramarleen/action:test_image_action
#    expose: 
#      - 5055

services:
  rasa:
    image: rasa/rasa:latest-full
    container_name: rasa
    hostname: rasa
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: "run -vv --enable-api --debug --cors '*' --endpoints endpoints.yml"

    #command:
    #  - run
    #  - -vv
    #  - -m
    #  - models
    #  - -p
    #  - "5000"
    #  - --cors
    #  - "*"
    #  - --enable-api
    #  - --debug
    networks: ['rasa-network']

  action_server:
    build: .
    container_name: action_server
    hostname: action_server
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
    networks: ['rasa-network']

  webserver:
    build: webserver/
    container_name: webserver
    hostname: webserver
    ports:
      - "8080:80"
    networks: ['rasa-network']
    

networks: {rasa-network: {}}