version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.3.4-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  
  app:
    image: daskita/chatbot:3261832adf309c866cdb609544a8ce03b8121341
    ports:
      - 5055:5055