version: '3.0'
services:
  rasa:
    #image: rasa/rasa:2.3.2-full
    image: floramarleen/rasa:test_image_rasa
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: run -m models --port 5005 --cors "*" --enable-api --debug
  app:
    image: floramarleen/action:test_image_action
    expose: 
      - 5055