version: "3.4"
services:
  db:
    volumes:
      - db-volume:/bitnami/postgresql
  app:
    image: "floramarleen/chatbot:action_server_image_tag"
    ports:
      - 5055:5055
  rabbit:
    ports:
      - "5672:5672"
volumes:
  db-volume:
    name: db-volume
